apiVersion: 1

datasources:
  - name: InfluxDB-Logs
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
    isDefault: true
